spring.application.name=appointment
server.port=8081
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/vet-clinic
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=true
spring.liquibase.default-schema=appointment

# REDIS_HOST - ?? ?????????????!
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}
spring.security.oauth2.client.registration.appointment.client-id=appointment-service
spring.security.oauth2.client.registration.appointment.client-secret=${KEYCLOAK_CLIENT_SECRET:KndP9iogTlX3TrdkzuPWgZYzztsp9o8D}
spring.security.oauth2.client.registration.appointment.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.appointment.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_EXTRA_ISSUER_URL:http://localhost:8080/realms/clinic-realm}

gateway.url=http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8888}