spring.application.name=appointment
server.port=8081
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:16177/railway
#spring.datasource.username=postgres
#spring.datasource.password=qpSrLAZPnMJIQMCfmFtSjUxdIsevRWBY
spring.datasource.url=jdbc:postgresql://localhost:5433/vet-clinic
spring.datasource.username=postgres
spring.datasource.password=12345

#spring.data.redis.repositories.enabled=false
#spring.data.jpa.repositories.bootstrap-mode=default

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=true
spring.liquibase.default-schema=appointment

#spring.data.redis.url=redis://default:YYcOvBCtxJyDXfyhHYpkuweoaSBCMMJw@hopper.proxy.rlwy.net:12179
#spring.redis.host=yamanote.proxy.rlwy.net
#spring.redis.port=58715
#spring.redis.password=GUMikUeQQDfZWaFjlQFJLPoCYIkQwAcT
spring.redis.host=localhost
spring.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/clinic-realm
spring.security.oauth2.client.registration.appointment.client-id=appointment-service
spring.security.oauth2.client.registration.appointment.client-secret=KndP9iogTlX3TrdkzuPWgZYzztsp9o8D
spring.security.oauth2.client.registration.appointment.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.appointment.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/clinic-realm

endpoints.telegram-bot.url=http://localhost:8090/notify/{tgUserName}